## Learn about numpy

In [2]:
import numpy as np

### creating array from list

In [3]:
arr_1d = np.array([1,2,3,4])
print("1d array:\n", arr_1d    )
arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array:\n", arr_2d)

1d array:
 [1 2 3 4]
2d array:
 [[1 2 3]
 [4 5 6]]


### List vs numpy array

In [4]:
py_list = [1, 2, 3, 4]
print("multiply python list by 2:", py_list * 2 )

arr1 = np.array([1, 2, 3, 4]) # element wise multiplication
print("multiply numpy array by 2:", arr1 * 2 )

import time
start = time.time()
py_list = (i*2 for i in range(1000000))
print("\n Time taken by python list comprehension:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print(" Time taken by numpy array operation:", time.time() - start)


multiply python list by 2: [1, 2, 3, 4, 1, 2, 3, 4]
multiply numpy array by 2: [2 4 6 8]

 Time taken by python list comprehension: 7.343292236328125e-05
 Time taken by numpy array operation: 0.0037565231323242188


### creating array from scratch

In [6]:
zeros = np.zeros((3,4))
print("\n3x4 array of zeros:\n", zeros)
ones = np.ones((3,4))
print("\n2x5 array of ones:\n", ones)
fulls = np.full((3,3), 4)
print("\n3x3 array of sevens:\n", fulls)
randoms = np.random.random((2,3))
print("\n2x4 array of randoms:\n", randoms)

sequence = np.arange(0, 10, 2)
print("\nArray with values from 10 to 20 with step 2:\n", sequence)

linspace_arr = np.linspace(0,10, num=5)
print("\n linspace array \n",linspace_arr)



3x4 array of zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x5 array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

3x3 array of sevens:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]

2x4 array of randoms:
 [[0.28187507 0.53431144 0.92794301]
 [0.01509982 0.64641553 0.65468639]]

Array with values from 10 to 20 with step 2:
 [0 2 4 6 8]

 linspace array 
 [ 0.   2.5  5.   7.5 10. ]


### vector,matrix and tensor

In [ ]:
vector = np.array([1, 2, 3])
print("\nVector (1D array):\n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\nMatrix (2D array):\n", matrix)

tensors = np.array([[[1,2],[3,4]],
                    [[5,6],[7,8]]])
print("\n Tensor (3D array):\n", tensors)


Vector (1D array):
 [1 2 3]

Matrix (2D array):
 [[1 2 3]
 [4 5 6]]

 Tensor (3D array):
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### array properties

In [ ]:
arr = np.array([[1, 2, 3],
                 [4, 5, 6]])
print("\n shape:", arr.shape)
print("\n number of dimensions:", arr.ndim)
print("\n size: ", arr.size)
print("\n data type:", arr.dtype)
print("\n item size:", arr.itemsize, "bytes")
print("\n total size:", arr.nbytes, "bytes")


 shape: (2, 3)

 number of dimensions: 2

 size:  6

 data type: int64

 item size: 8 bytes

 total size: 48 bytes


### array reshape

In [ ]:
arr = np.arange(12)
print("\nOriginal array:\n", arr)
reshaped_arr = arr.reshape((3,4))
print("\nReshaped array (3x4):\n", reshaped_arr)

flattened_arr = reshaped_arr.flatten()
print("\nFlattened array:\n", flattened_arr)

# ravel returns real array instead of copy
ravelled_arr = reshaped_arr.ravel()
print("\nRavelled array:\n", ravelled_arr)

# Transpose
transposed_arr = reshaped_arr.T
print("\nTransposed array:\n", transposed_arr)



Original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Flattened array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Ravelled array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Transposed array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
