### Numpy array operation 

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("\n basic slicing \n", arr[2:7])
print("\n step slicig \n", arr[1:8:2])


 basic slicing 
 [3 4 5 6 7]

 step slicig 
 [2 4 6 8]


In [4]:
arr_2d = np.array([[1,2,3],
                   [5,6,7],
                   [9,10,11]])

print("\n 2d array slicing \n", arr_2d[1,2])
print("Entire row 1: \n", arr_2d[1,:])
print("entire column 2:\n", arr_2d[:,2])


 2d array slicing 
 7
Entire row 1: 
 [5 6 7]
entire column 2:
 [ 3  7 11]


# Sorting

In [5]:
unsorted_arr = np.array([5,2,9,1,5,6])
sorted = np.sort(unsorted_arr)
print("\n sorted array: ", sorted)

arr_2d_unsorted = np.array([[3,1],
                            [1,2],
                            [2,3]])
print("Sorted 2d array by column: \n", np.sort(arr_2d_unsorted,axis=0))


 sorted array:  [1 2 5 5 6 9]
Sorted 2d array by column: 
 [[1 1]
 [2 2]
 [3 3]]


### Filtaring

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_num = numbers[numbers % 2 == 0]
print("Even numbers", even_num)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [7]:
mask = numbers > 5
print("\n numbers graeter then 5: \n",numbers[mask])


 numbers graeter then 5: 
 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where: \n", numbers[where_result])

[1 3 5]
NP where: 
 [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5,numbers*2,numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [10]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


## array compatibility

In [11]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatibality shapes: \n",a.shape == b.shape)

compatibality shapes: 
 True


In [12]:
original = np.array([[1,2],[3,4]])
nrow = np.array([5,6])

with_nrow = np.vstack((original,nrow))

print("original\n",original)
print("with_nrow\n", with_nrow)

ncol = np.array([[7],[8]])
wncol = np.hstack((original,ncol))
print("new col\n", wncol)

original
 [[1 2]
 [3 4]]
with_nrow
 [[1 2]
 [3 4]
 [5 6]]
new col
 [[1 2 7]
 [3 4 8]]


## Deletation of a element in numpy array

In [15]:
exarr = np.array([1,2,3,4,5])

new_arr =np.delete(exarr,2)
print(new_arr)

[1 2 4 5]
